version: "3.3"

services:

  web:
    build: .
    command: sh -c 'python manage.py'
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
  
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/      

volumes:
  postgres_data: